# filename: second_brain_builder/src/modules/obsidian_exporter.py
# purpose: Final export - creates Obsidian index and .obsidian config with backlinks (fixed import)

from pathlib import Path
from src.config import VAULT_ROOT

def create_obsidian_structure() -> None:
    """Build Obsidian vault index and minimal config for instant use."""
    obsidian_config = VAULT_ROOT / ".obsidian" / "workspace.json"
    obsidian_config.write_text('{"main": {"mode": "source"}}', encoding="utf-8")
    index_md = VAULT_ROOT / "index.md"
    index_content = """# Second Brain Vault 2026

## Quick Links
- [[youtube_notes/video_0...]] - Video transcripts
- [[notes/cloud_platforms/cloud_tools]] - Cloud platforms
- [[notes/local_storage/local_tools]] - Local storage
- [[notes/databases/db_tools]] - AI databases
- [[notes/emerging/emerging_tools]] - Emerging AI solutions

**Auto-generated by modular app - ready for graph view.**
"""
    index_md.write_text(index_content, encoding="utf-8")

if __name__ == "__main__":
    create_obsidian_structure()
